import { inngest } from "@/lib/inngest/client";
import { createAdminClient } from "@/lib/supabase-admin";

/**
 * Company Radar updates generator.
 * Runs daily to fetch updates for all verified companies.
 */
export const generateCompanyUpdates = inngest.createFunction(
  {
    id: "radar-companies",
    triggers: [{ cron: "30 2 * * *" }], // 2:30 AM
    concurrency: { limit: 1 },
    retries: 1,
  },
  async ({ step }) => {
    const supabase = createAdminClient();

    // 1. Fetch verified companies
    const { data: companies } = await step.run("fetch-companies", async () => {
      const { data } = await supabase.from("companies").select("*").eq("verified", true);
      return data || [];
    });

    let generated = 0;

    for (const company of companies) {
      await step.run(`fetch-updates-${company.slug}`, async () => {
        // In a real implementation we would:
        // 1. Fetch RSS for company blog
        // 2. Query GitHub releases for their orgs
        // 3. Check GDELT / HN for news mentions
        
        // Mocking an update insertion for demonstration purposes:
        if (Math.random() > 0.5) {
          const { error } = await supabase.from("company_updates").insert({
            company_id: company.id,
            kind: "shipped",
            title: `${company.name} launched a new feature`,
            url: `https://${company.domain}/blog/new-feature-${Date.now()}`,
            summary: "A brief summary of what was shipped, generated by the LLM from the blog post.",
          });
          if (!error) generated++;
        }
      });
    }

    return { companiesChecked: companies.length, updatesGenerated: generated };
  }
);

/**
 * Release Radar updates generator.
 * Runs daily to check for new releases in monitored ecosystems.
 */
export const generateReleaseUpdates = inngest.createFunction(
  {
    id: "radar-releases",
    triggers: [{ cron: "45 2 * * *" }], // 2:45 AM
    concurrency: { limit: 1 },
    retries: 1,
  },
  async ({ step }) => {
    const supabase = createAdminClient();

    // 1. Fetch packages to monitor
    // In a real implementation this would query unique `package_versions`
    const packages = [
      { ecosystem: "npm", name: "react", url: "https://github.com/facebook/react/releases" },
      { ecosystem: "npm", name: "next", url: "https://github.com/vercel/next.js/releases" }
    ];

    let generated = 0;

    for (const pkg of packages) {
      await step.run(`fetch-releases-${pkg.ecosystem}-${pkg.name}`, async () => {
        // 1. Fetch releases from GitHub or npm registry
        // 2. Identify if there's a new version since the last one in package_releases
        
        if (Math.random() > 0.7) {
          const version = `19.${Math.floor(Math.random() * 10)}.${Math.floor(Math.random() * 10)}`;
          const { error } = await supabase.from("package_releases").insert({
            ecosystem: pkg.ecosystem,
            name: pkg.name,
            version: version,
            release_notes_md: "Added new concurrent rendering features and fixed hydration mismatch bugs.",
            breaking_changes: false,
            url: `${pkg.url}/tag/v${version}`,
          });
          if (!error) generated++;
        }
      });
    }

    return { packagesChecked: packages.length, releasesFound: generated };
  }
);
