-- -----------------------------------------------------------------------------
-- Company Radar & Release Radar Tables
-- -----------------------------------------------------------------------------

-- 1. Companies
CREATE TABLE IF NOT EXISTS public.companies (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    name text not null,
    domain text,
    aliases text[] default '{}'::text[],
    github_orgs text[] default '{}'::text[],
    verified boolean default false,
    created_at timestamp with time zone default now() not null,
    CONSTRAINT slug_format CHECK (slug ~ '^[a-z0-9-]+$')
);

-- 2. User followed companies
CREATE TABLE IF NOT EXISTS public.user_companies (
    user_id uuid not null references auth.users(id) on delete cascade,
    company_id bigint not null references public.companies(id) on delete cascade,
    followed_at timestamp with time zone default now() not null,
    primary key (user_id, company_id)
);

-- 3. Company Updates (what they shipped, wrote, released, incidents)
CREATE TABLE IF NOT EXISTS public.company_updates (
    id bigint generated by default as identity primary key,
    company_id bigint not null references public.companies(id) on delete cascade,
    kind text not null CHECK (kind in ('shipped', 'wrote', 'news', 'incident')),
    title text not null,
    url text not null unique,
    summary text,
    published_at timestamp with time zone default now() not null
);

-- RLS
alter table public.companies enable row level security;
alter table public.user_companies enable row level security;
alter table public.company_updates enable row level security;

-- Policies for companies (everyone can read)
create policy "Anyone can read companies" on public.companies
    for select using (true);

-- Policies for user_companies
create policy "Users can read their own followed companies" on public.user_companies
    for select using (auth.uid() = user_id);

create policy "Users can insert their own followed companies" on public.user_companies
    for insert with check (auth.uid() = user_id);

create policy "Users can delete their own followed companies" on public.user_companies
    for delete using (auth.uid() = user_id);

-- Policies for company_updates
create policy "Anyone can read company updates" on public.company_updates
    for select using (true);

-- -----------------------------------------------------------------------------
-- Release Radar Tables
-- -----------------------------------------------------------------------------

-- We reuse the repositories and packages from Repo Guard.
-- But we need a place to track released versions that we have processed.
CREATE TABLE IF NOT EXISTS public.package_releases (
    id bigint generated by default as identity primary key,
    ecosystem text not null,
    name text not null,
    version text not null,
    release_notes_md text,
    breaking_changes boolean default false,
    url text,
    published_at timestamp with time zone default now() not null,
    unique(ecosystem, name, version)
);

-- RLS
alter table public.package_releases enable row level security;

create policy "Anyone can read package releases" on public.package_releases
    for select using (true);

-- Insert some starter companies
INSERT INTO public.companies (slug, name, domain, aliases, github_orgs, verified)
VALUES
  ('vercel', 'Vercel', 'vercel.com', '{vercel,nextjs}', '{vercel}', true),
  ('supabase', 'Supabase', 'supabase.com', '{supabase}', '{supabase}', true),
  ('stripe', 'Stripe', 'stripe.com', '{stripe}', '{stripe}', true),
  ('openai', 'OpenAI', 'openai.com', '{openai,chatgpt}', '{openai}', true),
  ('anthropic', 'Anthropic', 'anthropic.com', '{anthropic,claude}', '{anthropic}', true)
ON CONFLICT (slug) DO NOTHING;
