-- Learn Module Schema

create table public.learn_topics (
    id bigint generated by default as identity primary key,
    domain text not null,
    title text not null,
    format text not null default 'system_design' check (format in ('system_design', 'concept', 'bug_spotting', 'trade_off', 'interview')),
    difficulty text not null default 'intermediate' check (difficulty in ('beginner', 'intermediate', 'advanced', 'expert')),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.learn_items (
    id bigint generated by default as identity primary key,
    topic_id bigint references public.learn_topics(id) on delete cascade not null,
    question text not null,
    constraints text[] not null default '{}',
    hints text[] not null default '{}',
    answer_md text not null,
    diagram_ascii text,
    diagram_mermaid text,
    "references" text[] not null default '{}',
    review_score int,
    review_feedback text,
    status text not null default 'draft' check (status in ('draft', 'needs_revision', 'approved', 'rejected')),
    model text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.learn_progress (
    user_id uuid references auth.users(id) on delete cascade not null,
    item_id bigint references public.learn_items(id) on delete cascade not null,
    sent_at timestamp with time zone,
    revealed_at timestamp with time zone,
    self_rating int check (self_rating >= 1 and self_rating <= 5),
    primary key (user_id, item_id)
);

-- RLS
alter table public.learn_topics enable row level security;
alter table public.learn_items enable row level security;
alter table public.learn_progress enable row level security;

create policy "Learn topics are viewable by anyone" on public.learn_topics for select using (true);
create policy "Approved learn items are viewable by anyone" on public.learn_items for select using (status = 'approved');

create policy "Users can view their own learn progress" on public.learn_progress for select using (auth.uid() = user_id);
create policy "Users can insert their own learn progress" on public.learn_progress for insert with check (auth.uid() = user_id);
create policy "Users can update their own learn progress" on public.learn_progress for update using (auth.uid() = user_id);
